name: brmplcapp
description: BarrelRM initial Production Processor PLC UI companion

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

# MrP: Was -- sdk: ">=2.7.0 <3.0.0"  Was 2.1.0 on Aug4, 2020
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # add this line to your dependencies
  toast: ^0.1.5

  #---------------------------------------
  #         Network/Communications
  #---------------------------------------
  # https://pub.dev/packages/http
  http: ^0.12.0+2

  # https://pub.dev/packages/multicast_dns  -- doesn't work on Android -- didn't verify iOS
  # multicast_dns: ^0.2.2

  # MrP: Compile problems with 1.1.4
  #  # https://pub.flutter-io.cn/packages/mdns_plugin
  # mdns_plugin: ^1.1.3

  # https://pub.dev/packages/web_socket_channel
  #web_socket_channel: ^1.1.0

  # https://pub.dev/packages/get_ip
  get_ip: ^0.4.0

  # https://pub.dev/packages/connectivity  -- All methods had "No impl found for xxx on channel plugin.flutter.io/connectivity
  connectivity: ^0.4.8+2

  #---------------------------------------
  #               File, I/O
  #---------------------------------------
  # https://pub.dev/packages/file_picker   -- last used: ^1.4.3+1
  #file_picker: ^1.8.0+1

  # https://pub.dev/packages/folder_picker
  #folder_picker: ^0.3.0

  # https://pub.dev/packages/path_provider
  # platform: iOS, Android only -- getTemporaryDirectory(), getApplicationDocumentsDirectory()
  path_provider: ^1.6.7

  # https://pub.dev/packages/path
  path: ^1.6.4

  #---------------------------------------
  # Charting, Graphing, Drawing, Graphics
  #---------------------------------------
  # https://pub.dev/packages/charts_flutter
  charts_flutter: ^0.9.0

  # https://pub.dev/packages/flutter_cube
  # flutter_cube: ^0.0.4

  # https://pub.dev/packages/vector_math
  # vector_math: ^2.0.8

  #---------------------------------------
  #             Miscellaneous
  #---------------------------------------
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.6+3

  # https://pub.dev/packages/provider
  provider: ^3.0.0
  # provider: ^4.0.4

  # https://pub.dev/packages/file
  # MrP: Seems like smarter wrapper for File ops or such...
  # file: ^5.1.0

  # https://pub.dev/packages/permission_handler
  permission_handler: ^5.0.0+hotfix.4

  # https://pub.dev/packages/sprintf
  sprintf: ^4.0.2

  # https://pub.dev/packages/random_words
  #random_words: ^1.0.2

  # https://pub.dev/packages/sensors
  #sensors: ^0.4.1+6

  # https://pub.dev/packages/flutter_colorpicker
  #flutter_colorpicker: ^0.2.6

  # https://pub.dev/packages/csv
  csv: ^4.0.3

  # https://pub.dev/packages/app_settings     plugin for opening iOS and Android phone settings from an app.
  #app_settings: ^3.0.1

  # https://pub.dev/packages/webview_flutter
  # Opt-in to the embedded views preview by adding a boolean property to the app's Info.plist file with
  # the key io.flutter.embedded_views_preview and the value YES.
  #webview_flutter: ^0.3.19+9


  binary:

  #---------------------------------------
  # Images
  #---------------------------------------
  # https://pub.dev/packages/image_picker
  #image_picker: ^0.6.3

    # https://pub.dev/packages/image_gallery
  #image_gallery: ^1.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  #---------------------------------------
  #        Flutter Launcher Icons
  #---------------------------------------
  # https://pub.dev/packages/flutter_launcher_icons    -- had possible trouble with 0.7.4 so back to 0.7.3
  #
  # Open Terminal
  # > flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.3
https://pub:
  dev/packages/binary:
flutter_icons:
  image_path: "assets/images/splash.jpeg"
  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/splash.jpeg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  #fonts:
  #  - family: IBM_Plex_Mono
  #    fonts:
  #      - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Bold.ttf
  #      - weight: 700
  #      - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
  #      - weight: 400